moult fuite mémoire reparé et irace lancé

diff --git a/tuning/target-runner b/tuning/target-runner
--- a/tuning/target-runner
+++ b/tuning/target-runner
@@ -16,7 +16,6 @@
 # This script should print one numerical value: the cost that must be minimized.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
-EXE=~/bin/program
 FIXED_PARAMS=""
 
 CONFIG_ID=$1
@@ -29,10 +28,6 @@ CONFIG_PARAMS=$*
 STDOUT=c${CONFIG_ID}-${INSTANCE_ID}.stdout
 STDERR=c${CONFIG_ID}-${INSTANCE_ID}.stderr
 
-if [ ! -x "${EXE}" ]; then
-    error "${EXE}: not found or not executable (pwd: $(pwd))"
-fi
-
 # If the program just prints a number, we can use 'exec' to avoid
 # creating another process, but there can be no other commands after exec.
 #exec $EXE ${FIXED_PARAMS} -i $INSTANCE ${CONFIG_PARAMS}
@@ -41,12 +36,14 @@ fi
 # Otherwise, save the output to a file, and parse the result from it.
 # (If you wish to ignore segmentation faults you can use '{}' around
 # the command.)
-$EXE ${FIXED_PARAMS} --instance $INSTANCE --seed ${SEED} ${CONFIG_PARAMS} 1> ${STDOUT} 2> ${STDERR}
 
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
+# ./main ${FIXED_PARAMS} --bestval 1000 --tmax 20 --instance $INSTANCE --seed ${SEED} ${CONFIG_PARAMS} 1> ${STDOUT} 2> ${STDERR}
+./main ${FIXED_PARAMS} --instance $INSTANCE --seed ${SEED} ${CONFIG_PARAMS}
+
+#error() {
+#    echo "`TZ=UTC date`: error: $@"
+#    exit 1
+#}
 
 # # This may be used to introduce a delay if there are filesystem
 # # issues.
@@ -59,11 +56,11 @@ error() {
 # This is an example of reading a number from the output.
 # It assumes that the objective value is the first number in
 # the first column of the last line of the output.
-if [ -s "${STDOUT}" ]; then
-    COST=$(tail -n 1 ${STDOUT} | grep -e '^[[:space:]]*[+-]\?[0-9]' | cut -f1)
-    echo "$COST"
-    rm -f "${STDOUT}" "${STDERR}"
-    exit 0
-else
-    error "${STDOUT}: No such file or directory"
-fi
+#if [ -s "${STDOUT}" ]; then
+#    COST=$(tail -n 1 ${STDOUT} | grep -e '^[[:space:]]*[+-]\?[0-9]' | cut -f1)
+#    echo "$COST"
+#    rm -f "${STDOUT}" "${STDERR}"
+#    exit 0
+#else
+#    error "${STDOUT}: No such file or directory"
+#fi
